version: 2.1

orbs:
  orb-tools: circleci/orb-tools@10.0

workflows:
  test-pack:
    jobs:
      - orb-tools/lint # Lint Yaml files
      - orb-tools/pack # Pack orb source
  publish-dev:
    jobs:
      - orb-tools/publish-dev:
          orb-name: lucos/deploy
          context: orb-publishing
    requires:
      - test-pack
    filters:
      branches:
        ignore:
          - main
  publish-prod:
    jobs:
      - orb-tools/publish:
          orb-name: lucos/deploy
          context: orb-publishing
    requires:
      - test-pack
    filters:
      branches:
        only:
          - main
