version: 2.1

orbs:
  orb-tools: circleci/orb-tools@10.0

workflows:
  test-publish:
    jobs:
      - orb-tools/lint # Lint Yaml files
      - orb-tools/pack: # Pack orb source
          persist-to-workspace: true
      - orb-tools/publish-dev:
          orb-name: lucos/deploy
          context: orb-publishing
          attach-workspace: true
          requires:
            - orb-tools/lint
            - orb-tools/pack
          filters:
            branches:
              ignore:
                - main
      - orb-tools/increment:
          context: orb-publishing
          orb-ref: lucos/deploy
          attach-workspace: true
          requires:
            - orb-tools/lint
            - orb-tools/pack
          filters:
            branches:
              only:
                - main
