version: 2.1

orbs:
  orb-tools: circleci/orb-tools@10.0

workflows:
  test-publish:
    jobs:
      - run:
          name: Create deploy-valen job
          working_directory: src/jobs
          command: |
            sed -n '/^environment:$/,$p' deploy.yml\
            | sed 's/<< parameters.host-domain >>/valen.s.l42.eu/g'\
            | sed 's/<< parameters.architecture >>/amd64/g'\
            > deploy-valen.yml
      - orb-tools/lint # Lint Yaml files
      - orb-tools/pack: # Pack orb source
          persist-to-workspace: true
      - orb-tools/publish-dev:
          orb-name: lucos/deploy
          context: orb-publishing
          attach-workspace: true
          requires:
            - orb-tools/lint
            - orb-tools/pack
          filters:
            branches:
              ignore:
                - main
      - orb-tools/publish:
          context: orb-publishing
          orb-ref: lucos/deploy@0.0.0
          attach-workspace: true
          requires:
            - orb-tools/lint
            - orb-tools/pack
          filters:
            branches:
              only:
                - main
